# -*- coding: utf-8 -*-
"""Tarea-Caso-Practico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjS_qIrgSjPiX4P3ILooY-XY9pBvlcjA
"""

#IMPORTAR LIBRERIAS NECESARIAS
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

#CARGA DEL DATASET
df = pd.read_csv('https://raw.githubusercontent.com/JGaray04/Tarea-Datamining-Caso_Practico/refs/heads/main/Archivos/Dataset/Prestige_modificado.csv', sep=';')

#DIMENSIONES DEL DATAFRAME
print(df.shape)

#INSPECCION DE LAS PRIMERAS FILAS
print(df.head())

#TIPOS DE DATOS
print(df.info())

#IDENTIFICAN VALORES NULOS
print(df.isnull().sum())

#IDENTIFICAN VALORES DUPLICADOS
print(df.duplicated().sum())

#SE VISUALIZA ESTADISTICA DESCRIPTIVA
print(df.describe())

#SE CALCULA LA MATRIZ DE CORRELACION
variables_numericas = df.select_dtypes(include=['int64', 'float64'])
matriz_correlacion = variables_numericas.corr()

#SE ORDENA DE MAYOR A MENOR SEGUN PRESTIGE
print(matriz_correlacion.round(3))
print(matriz_correlacion['prestige'].sort_values(ascending=False).round(3))

#GRAFICAR RELACION ENTRE LA EDUCACION Y EL PRESTIGIO
plt.figure()
plt.scatter(df['education'], df['prestige'])
plt.xlabel('education')
plt.ylabel('prestige')
plt.title('Relación entre educación y prestigio')
plt.show()

#GRAFICAR RELACION ENTRE EL INGRESO Y EL PRESTIGIO
plt.figure()
plt.scatter(df['income'], df['prestige'])
plt.xlabel('income')
plt.ylabel('prestige')
plt.title('Relación entre ingreso y prestigio')
plt.show()

#GRAFICAR SOBRE EL PRESTIGIO PROMEDIO SEGUN EL TIPO DE OCUPACION
plt.figure()
df.groupby('type_num')['prestige'].mean().plot(kind='bar', color=['#2E75B6','#1F4E79','#4BACC6','#A9C4EB'])
plt.xlabel('Tipo de ocupación')
plt.ylabel('Prestigio promedio')
plt.title('Prestigio promedio por tipo de ocupación')
plt.xticks(ticks=[0,1,2,3], labels=['N/A','Profesional/Técnico','Blue Collar','White Collar'], rotation=30)
plt.tight_layout()
plt.show()

#SELECCION DE VARIABLES Y ESCALADO
columnas_cluster = ['education', 'income', 'women', 'prestige', 'type_num']
X = df[columnas_cluster].copy()

escalador = StandardScaler()
X_escalado = escalador.fit_transform(X)

#MODELO CON 4 CLUSTERES
modelo_k4 = KMeans(n_clusters=4, random_state=42, n_init=10)
df['Cluster_4'] = modelo_k4.fit_predict(X_escalado)

#MODELO CON 5 CLUSTERES
modelo_k5 = KMeans(n_clusters=5, random_state=42, n_init=10)
df['Cluster_5'] = modelo_k5.fit_predict(X_escalado)

print(df.groupby('Cluster_4')[columnas_cluster].mean().round(2))
print(df.groupby('Cluster_5')[columnas_cluster].mean().round(2))